### ISSUE TITLE
Incapacitated actors that are not marked as defeated in combat tracker still give gang up bonus

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#170] opened 2022-10-16 23:02 UTC
Incapacitated actors that are not marked as defeated in combat tracker still give gang up bonus. Related to #165 
![image](https://user-images.githubusercontent.com/22677493/196062682-1d5c0dbd-baca-4eda-9a8c-d5534984b1ed.png)
![image](https://user-images.githubusercontent.com/22677493/196062689-22b6e623-cf0b-4843-bc9f-be32fc0f5e46.png)

**Comment by sanpats** [comment] 2022-10-16 23:05
GM can manually marked incapacitated actors as defeated, so it is another corner case. May be Incapacitated status and Defeated can be linked via coding somehow?

**Comment by lipefl** [comment] 2022-10-17 12:53
Incapacitated must be added as overlay (right-click the icon), than it'll become like default incapacitaded token (with a big skull over the token). And.. it'll not count for gang up

**Comment by lipefl** [comment] 2022-10-17 12:59
Since this token is in combat it's better if you press the skull icon in combat track. It'll stop checking for shaken too.

I'll see if i can change the code to recognize the incapacitated icon wherever it is. But it's not the expected behavior.

**Comment by lipefl** [comment] 2022-10-24 21:10
I tried to get all the possibilities, but i ended up finding that it was too much trouble for something that's not supposed to work that way. So i'll close this issue.

**Closed by lipefl** 2022-10-24 21:10 UTC
Labels: enhancement
