### ISSUE TITLE
Automatic Unshake doesn't seem to work

### ISSUE THREAD

**Issue by JusticeTheAwesome** [lipefl/swade-tools#175] opened 2022-10-24 01:55 UTC
That's it. Just stopped working. I didn't install any module or anything it just stopped.

**Comment by lipefl** [comment] 2022-10-24 17:52
I don't see this happening here. Can you check if "Disable automatic rolls during combat" is set to "No"?

If so, can you provide more information? Wich versions (foundry, swade, swade tools)? Maybe an error on console?

**Comment by Cosmic-Lattee** [comment] 2022-10-25 19:15
So I was having this happen as well actually but I didn't make a issue about it because it was being inconsistent. 

I at first used Find the Culprit and found that it wasn't working regardless of what modules were on. However before I made the issue I wanted to test all options. No error messages in the console 

Then I made a fresh game and just have the one module on, and...it just worked without issue. So I just went ahead and transferred stuff over into the new game since it was being inconsistent. 

I updated the game today and lo and behold it stopped working once again. I made a fresh game and it works again in that game. So something is happening with the updates that is breaking it for older established games but still works for a newly made game.

At least that seems to be what is happening, I am not sure why that would be the case.

**Comment by JusticeTheAwesome** [comment] 2022-10-27 00:20
Sorry for answering late. Yes, I've tried disabling and enabling the "Automatic rolls during combat option" reseting foundry and uninstalling and installing SWADE tools.

My Swade Version is : 2.0.6.
and my Foundry Version Is: 10
Swade Tools is in its last version: 1.10.9.

**Comment by JusticeTheAwesome** [comment] 2022-10-27 00:21
![image](https://user-images.githubusercontent.com/91155212/198162558-ead823b2-ab14-4f7f-a3cc-ef59406828dd.png)

This is a common error in the console, maybe it has something to do with this issue

**Comment by lipefl** [comment] 2022-10-27 14:05
In the case scenario where SWADE Tools automation don't work... If you disable SWADE Tools, does this appear for you instead (on a shaken actor in combat)? I could try to use the same trigger.

![image](https://user-images.githubusercontent.com/10639148/198306342-ce117647-3028-4692-b055-43c9c1fc7c98.png)

@JusticeTheAwesome are you using Foundry build 288 (last one)? The console log warning has nothing to do with SWADE Tools. Have you tested disabling all other modules?

@Cosmic-Lattee if you provide me the steps to reproduce the problem, maybe i can find a solution.

**Comment by JusticeTheAwesome** [comment] 2022-10-31 22:57
Sorry for being late. I can confirm. That window appear when I disable Swade Tools. And yes, I'm using the last Foundry Build. 288. I also tried using only SWADE tools but, still doesn't work.

**Comment by JusticeTheAwesome** [comment] 2022-11-01 02:11
> In the case scenario where SWADE Tools automation don't work... If you disable SWADE Tools, does this appear for you instead (on a shaken actor in combat)? I could try to use the same trigger.

That could do the trick, I think

**Comment by JusticeTheAwesome** [comment] 2022-11-03 00:43
I made an interesting discovery. We were testing with my players and we find out that the Automatic Unshake function only works with the first GM profile on the list in the log in. We've got multiple GM's profiles, and we tested changing the first letter of the profile's name (The list is on alphabetical order) writing an "A" at the beginning of the GM's profile name. And surprisingly, it works! I don't know how, but it works. 

We made some progress!

**Comment by lipefl** [comment] 2022-11-09 19:31
Unfortunately I couldn't use the trigger from SWADE system because it doesnt work the way i thought.

I added a Debugger option in SWADE Tools (v1.10.10). If you could please activate it as a GM, then press F12 and go to Console, you should see something like this when starting a new turn (it can be a little different in the start of a round). Send it here, so i can have an ideia of what is happening. 

![image](https://user-images.githubusercontent.com/10639148/200920386-99ebb33b-ccd1-46a9-81f8-082c4f2fb317.png)

@JusticeTheAwesome the turn automation only works for the first GM, so it doesn't repeat itself for other users. If you're switching GMs, i suggest you always refresh after a switch (probably what happened when you changed the GM name).

**Comment by lipefl** [comment] 2023-01-15 15:20
Since there's no further answer, i'll close this issue. It could be reopened if the problem continues.

**Closed by lipefl** 2023-01-15 15:20 UTC
Labels: bug
