### ISSUE TITLE
Bug with "Popout!" module

### ISSUE THREAD

**Issue by Lifthraser** [lipefl/swade-tools#115] opened 2022-03-09 20:16 UTC
when a character sheet is poped out and swade tool makes a trait, power or weapon popup, the "Mod" input field has very strange behavior. It does not support a lot of keyboard input: anything from numpad input, does not support delete backspace or even navigation arrows left or right inputs in the field.
Swade Core does not have this problem, probably because the popup windows at inside the original windows and not in the poped out windows like in swade tools.

**Comment by lipefl** [comment] 2022-03-09 20:38
Fixed in v1.8.8. The dialog now opens inside the popout window, as intended. Thanks!

**Closed by lipefl** 2022-03-09 20:38 UTC
Labels: bug

**Comment by Lifthraser** [comment] 2022-03-09 22:45
updated to v1.8.9 but I dont see any difference.

**Comment by lipefl** [comment] 2022-03-09 22:54
Can you send some screenshots? I tested here and it's working. 
Here's a screenshot using the sheet in another tab

![image](https://user-images.githubusercontent.com/10639148/157552513-fcb42c50-92c2-4ff6-869e-949a4318450f.png)

**Comment by lipefl** [comment] 2022-03-09 23:20
Sorry, i think i misunderstood your problem, but both works the same way for me (swade system and swade tools). They open the dialog in the same window as the sheet (that's how it's supposed to work).
I tested again, i can use backspace, delete, numpad, etc.
It might be your browser, have you tried another browser or anonymous tab?

![image](https://user-images.githubusercontent.com/10639148/157555128-b0240256-19af-4af2-92f7-548f10cd6519.png)

**Comment by lipefl** [comment] 2022-03-10 18:12
So, i updated my PopOut! module and i finally see what you are saying. This is probably a problem that needs to be solved in PopOut! module (i wasn't experiencing this when using PopOut older version). This happens with ANYTHING (even the fields in the sheet itself). I'll open an issue there.

The only thing i can do on my side, is an option to open dialogs from the sheet in the main window, wich i dont think is best for user experience.

**Comment by Lifthraser** [comment] 2022-03-10 18:21
Ohhh sorry I did not realise it was all the fields in the sheet.
Totally a popout problem.
I can do the ticket later if needed.

**Comment by lipefl** [comment] 2022-03-10 18:23
I already did it, you can follow there. Please add any information you think it'll be useful :)
https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues/76
