### ISSUE TITLE
Support for unShakeBonus & unStunBonus

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#221] opened 2023-05-18 10:09 UTC
Swade Tools seem to ignore the
system.attributes.spirit.unShakeBonus
system.attributes.vigor.unStunBonus
on a token.

I have an commander, that gives them to nearby allies (Foundry 10.291, SWADE 2.4.2, Active Auras 0.60). I see the Aura effect on the Token and Toughness is upgraded correctly. But when the Token is shaken and I unshake it, the +1 unShakeBonus is not integrated in the roll. Same goes for unStunBonus.

Let me know, if you need more data or screenshots.

**Comment by lipefl** [comment] 2023-05-18 14:58
To be honest, I didnt even know this values existed. This seems to be something recent in SWADE system. If it's just to recognize them it's fine. I can fix it. 
But to test i'll need the steps to reproduce the problem. I'm not familiar with Active Auras and what it does.

**Comment by lipefl** [comment] 2023-05-18 23:02
Support is now added in v1.12.2. Thanks!

**Comment by Vogliadicone** [comment] 2023-05-19 08:32
Thank! The
system.attributes.spirit.unShakeBonus
works fine. But
system.attributes.vigor.unStunBonus
still didn't seem to work. Have you added support for both?
![unstun](https://github.com/lipefl/swade-tools/assets/119852651/72c9ef1b-26d0-4941-b066-26b5db259699)
What also didn't seem to work is the Soak Bonus that I forget to mention in my first post:
system.attributes.vigor.soakBonus

**Comment by lipefl** [comment] 2023-05-19 12:29
i added support to all. I'll re-open this issue to check again if there's any bug.

**Comment by lipefl** [comment] 2023-05-19 13:26
Unstun wasn't being detected. Now it's fixed in v1.12.3
Thanks!

**Closed by lipefl** 2023-05-19 13:26 UTC
Labels: compatibility
