### ISSUE TITLE
Issue still exist after update

### ISSUE THREAD

**Issue by ratpooka** [lipefl/swade-tools#239] opened 2023-07-03 05:59 UTC
The issue with Swade tools not unshaking automatically still exists after the update. Seems like it removes the Image of the icon but not that status itself mechanically.

![1111](https://github.com/lipefl/swade-tools/assets/138188602/a6273304-27d6-4d3f-bcb7-baaba97da37a)

**Comment by lipefl** [comment] 2023-07-03 12:38
I re-tested, this doesnt happen here. Can you look at console (F12) to see if there's something in red when the Shaken should be removed? 
Im using 
Foundry 11.304
SWADE 3.0.4
SWADE Tools 13.3.3

**Comment by lipefl** [comment] 2023-07-05 13:09
It seems it's not finding the actor or the token to remove the status effect. 
I'm not able to reproduce the problem tough, can you test in a new world with only swade tools enabled? It might be a bug with something in this specific world.

**Comment by ratpooka** [comment] 2023-07-06 05:39
Tested as per your request. The issue still exists.
![1234](https://github.com/lipefl/swade-tools/assets/138188602/8be64bcc-4572-4e74-bdee-1d40d6431897)

Ran the same test with better rolls 2. Issues do not exist.
![4321](https://github.com/lipefl/swade-tools/assets/138188602/ceb243a1-eab0-45ac-8e25-639a59ac0e1e)

**Comment by lipefl** [comment] 2023-07-06 20:08
Have you used another world to test?
The problem is i need to be able to reproduce the problem, to fix it.
Maybe if i can access your instance i'll be able to see whats is causing the problem. You can call me on discord, if you want to do that (lipefl)

BR2 is another code, it wont help here.

**Comment by lipefl** [comment] 2023-07-07 01:08
Fixed in v1.13.4
Thanks for the help!

**Closed by lipefl** 2023-07-07 01:08 UTC
Labels: question
